### ISSUE TITLE
文字化け

### ISSUE THREAD

**Issue by mayano2017** [mayano2017/pjtiafun#4]
phpdevというフリーソフトを使ってローカルでphpとmysqlをうごかそうとしているのですが、どうもmysqlの文字コードでUTF-8が選択できないせいか文字化けしてしまうのです。
こんなものなのでしょうか？

**Comment by hirayama** [comment]
localでphpを動かすぱっと思いつく方法

1. localにhttpサーバーを立てる
    - [xampp](https://www.apachefriends.org/jp/index.html) あたりが煩わしいバージョン管理などできそう
    - もちろん地道にapacheインストールしてphpモジュールを入れるでもよい
1. localにlinux系OSのVMをたてて、そこでapacheインストール
    - [vagrant](https://www.google.co.jp/search?q=vagrant&oq=vagrant&aqs=chrome..69i57j0l5.2106j0j4&sourceid=chrome&ie=UTF-8) でググってどうぞ
1. localにlinux系OSのコンテナをたてて、そこでapacheインストール
    - 根性使いたければググってどうぞ

**Comment by mayano2017** [comment]
結局、レンタルサーバの方でやって問題なくできました
